### ISSUE TITLE
Debug badger-vaults mapping issue

### ISSUE THREAD

**Issue by mrbasado** [Badger-Finance/badger-subgraph#66]

**Comment by gosuto-inzasheru** [comment]
> INDEXING ERROR
Error: Mapping aborted at generated/schema.ts, line 147, column 12, with message: unexpected null wasm backtrace: 0: 0x2c56 - <unknown>!generated/schema/Sett#get:name 1: 0x4f7d - <unknown>!src/entities/badger-sett/loadSett 2: 0x6925 - <unknown>!src/handlers/sett-handler/handleSettTokenTransfer 3: 0x6acd - <unknown>!src/handlers/sett-handler/handleTransfer in handler `handleTransfer` at block #11381150 (b10be2b476e64f42e4eb6d7b29a309e3e6e953215ace7454e0e702656dae2059)

https://thegraph.com/studio/subgraph/badger-vaults/ (need to be logged in as my deployer)
